/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MyApiGateway": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "MyAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "MyClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "MyUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "MyWeb": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}