/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as CrmWrapupRouteImport } from './routes/crm/wrapup'
import { Route as CrmSearchRouteImport } from './routes/crm/search'
import { Route as CrmReminderHistoryRouteImport } from './routes/crm/reminder-history'
import { Route as CrmReferenceListRouteImport } from './routes/crm/reference-list'
import { Route as CrmFollowHistoryRouteImport } from './routes/crm/follow-history'
import { Route as CrmCustomerRouteImport } from './routes/crm/customer'
import { Route as CrmContactAmendmentRouteImport } from './routes/crm/contact-amendment'
import { Route as CrmAccountRouteImport } from './routes/crm/account'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmWrapupRoute = CrmWrapupRouteImport.update({
  id: '/wrapup',
  path: '/wrapup',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSearchRoute = CrmSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => CrmRoute,
} as any)
const CrmReminderHistoryRoute = CrmReminderHistoryRouteImport.update({
  id: '/reminder-history',
  path: '/reminder-history',
  getParentRoute: () => CrmRoute,
} as any)
const CrmReferenceListRoute = CrmReferenceListRouteImport.update({
  id: '/reference-list',
  path: '/reference-list',
  getParentRoute: () => CrmRoute,
} as any)
const CrmFollowHistoryRoute = CrmFollowHistoryRouteImport.update({
  id: '/follow-history',
  path: '/follow-history',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCustomerRoute = CrmCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactAmendmentRoute = CrmContactAmendmentRouteImport.update({
  id: '/contact-amendment',
  path: '/contact-amendment',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAccountRoute = CrmAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => CrmRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/crm/account': typeof CrmAccountRoute
  '/crm/contact-amendment': typeof CrmContactAmendmentRoute
  '/crm/customer': typeof CrmCustomerRoute
  '/crm/follow-history': typeof CrmFollowHistoryRoute
  '/crm/reference-list': typeof CrmReferenceListRoute
  '/crm/reminder-history': typeof CrmReminderHistoryRoute
  '/crm/search': typeof CrmSearchRoute
  '/crm/wrapup': typeof CrmWrapupRoute
  '/api': typeof ApiIndexRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/crm/account': typeof CrmAccountRoute
  '/crm/contact-amendment': typeof CrmContactAmendmentRoute
  '/crm/customer': typeof CrmCustomerRoute
  '/crm/follow-history': typeof CrmFollowHistoryRoute
  '/crm/reference-list': typeof CrmReferenceListRoute
  '/crm/reminder-history': typeof CrmReminderHistoryRoute
  '/crm/search': typeof CrmSearchRoute
  '/crm/wrapup': typeof CrmWrapupRoute
  '/api': typeof ApiIndexRoute
  '/crm': typeof CrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/crm/account': typeof CrmAccountRoute
  '/crm/contact-amendment': typeof CrmContactAmendmentRoute
  '/crm/customer': typeof CrmCustomerRoute
  '/crm/follow-history': typeof CrmFollowHistoryRoute
  '/crm/reference-list': typeof CrmReferenceListRoute
  '/crm/reminder-history': typeof CrmReminderHistoryRoute
  '/crm/search': typeof CrmSearchRoute
  '/crm/wrapup': typeof CrmWrapupRoute
  '/api/': typeof ApiIndexRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm'
    | '/auth/callback'
    | '/crm/account'
    | '/crm/contact-amendment'
    | '/crm/customer'
    | '/crm/follow-history'
    | '/crm/reference-list'
    | '/crm/reminder-history'
    | '/crm/search'
    | '/crm/wrapup'
    | '/api'
    | '/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/crm/account'
    | '/crm/contact-amendment'
    | '/crm/customer'
    | '/crm/follow-history'
    | '/crm/reference-list'
    | '/crm/reminder-history'
    | '/crm/search'
    | '/crm/wrapup'
    | '/api'
    | '/crm'
  id:
    | '__root__'
    | '/'
    | '/crm'
    | '/auth/callback'
    | '/crm/account'
    | '/crm/contact-amendment'
    | '/crm/customer'
    | '/crm/follow-history'
    | '/crm/reference-list'
    | '/crm/reminder-history'
    | '/crm/search'
    | '/crm/wrapup'
    | '/api/'
    | '/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmRoute: typeof CrmRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiIndexRoute: typeof ApiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/wrapup': {
      id: '/crm/wrapup'
      path: '/wrapup'
      fullPath: '/crm/wrapup'
      preLoaderRoute: typeof CrmWrapupRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/search': {
      id: '/crm/search'
      path: '/search'
      fullPath: '/crm/search'
      preLoaderRoute: typeof CrmSearchRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/reminder-history': {
      id: '/crm/reminder-history'
      path: '/reminder-history'
      fullPath: '/crm/reminder-history'
      preLoaderRoute: typeof CrmReminderHistoryRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/reference-list': {
      id: '/crm/reference-list'
      path: '/reference-list'
      fullPath: '/crm/reference-list'
      preLoaderRoute: typeof CrmReferenceListRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/follow-history': {
      id: '/crm/follow-history'
      path: '/follow-history'
      fullPath: '/crm/follow-history'
      preLoaderRoute: typeof CrmFollowHistoryRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/customer': {
      id: '/crm/customer'
      path: '/customer'
      fullPath: '/crm/customer'
      preLoaderRoute: typeof CrmCustomerRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contact-amendment': {
      id: '/crm/contact-amendment'
      path: '/contact-amendment'
      fullPath: '/crm/contact-amendment'
      preLoaderRoute: typeof CrmContactAmendmentRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/account': {
      id: '/crm/account'
      path: '/account'
      fullPath: '/crm/account'
      preLoaderRoute: typeof CrmAccountRouteImport
      parentRoute: typeof CrmRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CrmRouteChildren {
  CrmAccountRoute: typeof CrmAccountRoute
  CrmContactAmendmentRoute: typeof CrmContactAmendmentRoute
  CrmCustomerRoute: typeof CrmCustomerRoute
  CrmFollowHistoryRoute: typeof CrmFollowHistoryRoute
  CrmReferenceListRoute: typeof CrmReferenceListRoute
  CrmReminderHistoryRoute: typeof CrmReminderHistoryRoute
  CrmSearchRoute: typeof CrmSearchRoute
  CrmWrapupRoute: typeof CrmWrapupRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmAccountRoute: CrmAccountRoute,
  CrmContactAmendmentRoute: CrmContactAmendmentRoute,
  CrmCustomerRoute: CrmCustomerRoute,
  CrmFollowHistoryRoute: CrmFollowHistoryRoute,
  CrmReferenceListRoute: CrmReferenceListRoute,
  CrmReminderHistoryRoute: CrmReminderHistoryRoute,
  CrmSearchRoute: CrmSearchRoute,
  CrmWrapupRoute: CrmWrapupRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmRoute: CrmRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiIndexRoute: ApiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
